export const GET_ALL_PROPOSALS = "GET_ALL_PROPOSALS";
export const GET_VOTE_ACCOUNTS = "GET_VOTE_ACCOUNTS";
export const GET_STAKE_ACCOUNTS = "GET_STAKE_ACCOUNTS";
export const GET_DELEGATED_STAKE_ACCOUNTS = "GET_DELEGATED_STAKE_ACCOUNTS";
export const GET_VOTE_PROPOSALS = "GET_VOTE_PROPOSALS";
